node {
  checkout scm
  
}

pipeline {
  agent any
  stages {
    stage('Get code'){
      steps {
        checkout scm
      }
    }
    stage('Docker build and push image to DockerHub'){
      steps {
        docker.withRegistry('https://registry.hub.docker.com', 'DockerHub') {
          def customImage = docker.build("mstr0m/jenkins_web_app:${env.BUILD_ID}", "./Project2-JenkinsPipeline")
          // customImage.push()
        }
      }
    }
  //   stage('Docker build image'){
  //     steps {
  //       sh 'docker build -t jenkins_pipeline_app:$BUILD_NUMBER .'
  //     }
  //   }
  //   stage('Remove Docker container') {
  //       steps {
  //           script{
  //             try {
  //                 sh 'docker rm -f Addressbook'
  //             } catch (Exception e) {
  //                 echo 'Expected exception: ' + e.toString()
  //             }
  //           }
  //       }
  //   }
  //   stage('Run in Docker') {
  //       steps {
  //           script{
  //               sh 'docker run -d --name Addressbook -p 8888:8080 -v /var/lib/jenkins/workspace/pipeline/target:/usr/local/tomcat/webapps tomcat:9.0'
  //           }
  //       }
  //   }
  }
}