pipeline {
  agent any
  stages {
    stage('Get code'){
      steps {
        checkout scm
      }
    }
    stage('Docker build and push image to DockerHub'){
      steps {
        script{
          docker.withRegistry('https://registry.hub.docker.com', 'DockerHub') {
            def customImage = docker.build("mstr0m/jenkins_web_app:${env.BUILD_ID}", "./Project2-JenkinsPipeline")
            customImage.push()
          }
        }
      }
    }
    stage('Remove Docker container from previous build if it runs') {
      steps {
        script{
          try {
            sh 'docker rm -f jenkins_web_app'
          } catch (Exception e) {
            echo 'No container is running.' + e.toString()
          }
        }
      }
    }
    stage('Docker run named container from DockerHub lates image'){
      steps {
        sh 'docker run -d -p 80:8080 --name jenkins_web_app mstr0m/jenkins_web_app:${env.BUILD_ID}'
      }
    }
  }
}